export const getCatsBreeds = () =>
  Promise.resolve({
    data: [
      {
        weight: {
          imperial: '7  -  10',
          metric: '3 - 5',
        },
        id: 'abys',
        name: 'Abyssinian',
        cfa_url: 'http://cfa.org/Breeds/BreedsAB/Abyssinian.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/abyssinian',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/abyssinian',
        temperament: 'Active, Energetic, Independent, Intelligent, Gentle',
        origin: 'Egypt',
        country_codes: 'EG',
        country_code: 'EG',
        description:
          'The Abyssinian is easy to care for, and a joy to have in your home. They’re affectionate cats and love both people and other animals.',
        life_span: '14 - 15',
        indoor: 0,
        lap: 1,
        alt_names: '',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 3,
        dog_friendly: 4,
        energy_level: 5,
        grooming: 1,
        health_issues: 2,
        intelligence: 5,
        shedding_level: 2,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 1,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Abyssinian_(cat)',
        hypoallergenic: 0,
      },
      {
        weight: {
          imperial: '7 - 10',
          metric: '3 - 5',
        },
        id: 'aege',
        name: 'Aegean',
        vetstreet_url: 'http://www.vetstreet.com/cats/aegean-cat',
        temperament: 'Affectionate, Social, Intelligent, Playful, Active',
        origin: 'Greece',
        country_codes: 'GR',
        country_code: 'GR',
        description:
          'Native to the Greek islands known as the Cyclades in the Aegean Sea, these are natural cats, meaning they developed without humans getting involved in their breeding. As a breed, Aegean Cats are rare, although they are numerous on their home islands. They are generally friendly toward people and can be excellent cats for families with children.',
        life_span: '9 - 12',
        indoor: 0,
        alt_names: '',
        adaptability: 5,
        affection_level: 4,
        child_friendly: 4,
        dog_friendly: 4,
        energy_level: 3,
        grooming: 3,
        health_issues: 1,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 4,
        stranger_friendly: 4,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Aegean_cat',
        hypoallergenic: 0,
      },
      {
        weight: {
          imperial: '7 - 16',
          metric: '3 - 7',
        },
        id: 'abob',
        name: 'American Bobtail',
        cfa_url: 'http://cfa.org/Breeds/BreedsAB/AmericanBobtail.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/american-bobtail',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/american-bobtail',
        temperament: 'Intelligent, Interactive, Lively, Playful, Sensitive',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          'American Bobtails are loving and incredibly intelligent cats possessing a distinctive wild appearance. They are extremely interactive cats that bond with their human family with great devotion.',
        life_span: '11 - 15',
        indoor: 0,
        lap: 1,
        alt_names: '',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 1,
        health_issues: 1,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 3,
        stranger_friendly: 3,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 1,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/American_Bobtail',
        hypoallergenic: 0,
      },
      {
        weight: {
          imperial: '5 - 10',
          metric: '2 - 5',
        },
        id: 'acur',
        name: 'American Curl',
        cfa_url: 'http://cfa.org/Breeds/BreedsAB/AmericanCurl.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/american-curl',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/american-curl',
        temperament:
          'Affectionate, Curious, Intelligent, Interactive, Lively, Playful, Social',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          'Distinguished by truly unique ears that curl back in a graceful arc, offering an alert, perky, happily surprised expression, they cause people to break out into a big smile when viewing their first Curl. Curls are very people-oriented, faithful, affectionate soulmates, adjusting remarkably fast to other pets, children, and new situations.',
        life_span: '12 - 16',
        indoor: 0,
        lap: 1,
        alt_names: '',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 2,
        health_issues: 1,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 3,
        stranger_friendly: 3,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/American_Curl',
        hypoallergenic: 0,
      },
      {
        weight: {
          imperial: '8 - 15',
          metric: '4 - 7',
        },
        id: 'asho',
        name: 'American Shorthair',
        cfa_url: 'http://cfa.org/Breeds/BreedsAB/AmericanShorthair.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/american-shorthair',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/american-shorthair',
        temperament: 'Active, Curious, Easy Going, Playful, Calm',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          'The American Shorthair is known for its longevity, robust health, good looks, sweet personality, and amiability with children, dogs, and other pets.',
        life_span: '15 - 17',
        indoor: 0,
        lap: 1,
        alt_names: 'Domestic Shorthair',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 1,
        health_issues: 3,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 4,
        stranger_friendly: 3,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 1,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/American_Shorthair',
        hypoallergenic: 0,
      },
      {
        weight: {
          imperial: '8 - 15',
          metric: '4 - 7',
        },
        id: 'awir',
        name: 'American Wirehair',
        cfa_url: 'http://cfa.org/Breeds/BreedsAB/AmericanWirehair.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/american-wirehair',
        temperament:
          'Affectionate, Curious, Gentle, Intelligent, Interactive, Lively, Loyal, Playful, Sensible, Social',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          'The American Wirehair tends to be a calm and tolerant cat who takes life as it comes. His favorite hobby is bird-watching from a sunny windowsill, and his hunting ability will stand you in good stead if insects enter the house.',
        life_span: '14 - 18',
        indoor: 0,
        lap: 1,
        alt_names: '',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 1,
        health_issues: 3,
        intelligence: 3,
        shedding_level: 1,
        social_needs: 3,
        stranger_friendly: 3,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/American_Wirehair',
        hypoallergenic: 0,
      },
      {
        weight: {
          imperial: '8 - 16',
          metric: '4 - 7',
        },
        id: 'amau',
        name: 'Arabian Mau',
        vcahospitals_url: '',
        temperament:
          'Affectionate, Agile, Curious, Independent, Playful, Loyal',
        origin: 'United Arab Emirates',
        country_codes: 'AE',
        country_code: 'AE',
        description:
          'Arabian Mau cats are social and energetic. Due to their energy levels, these cats do best in homes where their owners will be able to provide them with plenty of playtime, attention and interaction from their owners. These kitties are friendly, intelligent, and adaptable, and will even get along well with other pets and children.',
        life_span: '12 - 14',
        indoor: 0,
        alt_names: 'Alley cat',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 4,
        grooming: 1,
        health_issues: 1,
        intelligence: 3,
        shedding_level: 1,
        social_needs: 3,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 1,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Arabian_Mau',
        hypoallergenic: 0,
      },
      {
        weight: {
          imperial: '7 - 15',
          metric: '3 - 7',
        },
        id: 'amis',
        name: 'Australian Mist',
        temperament: 'Lively, Social, Fun-loving, Relaxed, Affectionate',
        origin: 'Australia',
        country_codes: 'AU',
        country_code: 'AU',
        description:
          'The Australian Mist thrives on human companionship. Tolerant of even the youngest of children, these friendly felines enjoy playing games and being part of the hustle and bustle of a busy household. They make entertaining companions for people of all ages, and are happy to remain indoors between dusk and dawn or to be wholly indoor pets.',
        life_span: '12 - 16',
        indoor: 0,
        lap: 1,
        alt_names: 'Spotted Mist',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 4,
        grooming: 3,
        health_issues: 1,
        intelligence: 4,
        shedding_level: 3,
        social_needs: 4,
        stranger_friendly: 4,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Australian_Mist',
        hypoallergenic: 0,
      },
      {
        weight: {
          imperial: '4 - 10',
          metric: '2 - 5',
        },
        id: 'bali',
        name: 'Balinese',
        cfa_url: 'http://cfa.org/Breeds/BreedsAB/Balinese.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/balinese',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/balinese',
        temperament: 'Affectionate, Intelligent, Playful',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          'Balinese are curious, outgoing, intelligent cats with excellent communication skills. They are known for their chatty personalities and are always eager to tell you their views on life, love, and what you’ve served them for dinner. ',
        life_span: '10 - 15',
        indoor: 0,
        alt_names: 'Long-haired Siamese',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 3,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Balinese_(cat)',
        hypoallergenic: 1,
      },
      {
        weight: {
          imperial: '4 - 9',
          metric: '2 - 4',
        },
        id: 'bamb',
        name: 'Bambino',
        temperament: 'Affectionate, Lively, Friendly, Intelligent',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          'The Bambino is a breed of cat that was created as a cross between the Sphynx and the Munchkin breeds. The Bambino cat has short legs, large upright ears, and is usually hairless. They love to be handled and cuddled up on the laps of their family members.',
        life_span: '12 - 14',
        indoor: 0,
        lap: 1,
        alt_names: '',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 1,
        health_issues: 1,
        intelligence: 5,
        shedding_level: 1,
        social_needs: 3,
        stranger_friendly: 3,
        vocalisation: 3,
        experimental: 1,
        hairless: 1,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 1,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Bambino_cat',
        hypoallergenic: 0,
      },
      {
        weight: {
          imperial: '6 - 12',
          metric: '3 - 7',
        },
        id: 'beng',
        name: 'Bengal',
        cfa_url: 'http://cfa.org/Breeds/BreedsAB/Bengal.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/bengal',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/bengal',
        temperament: 'Alert, Agile, Energetic, Demanding, Intelligent',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          "Bengals are a lot of fun to live with, but they're definitely not the cat for everyone, or for first-time cat owners. Extremely intelligent, curious and active, they demand a lot of interaction and woe betide the owner who doesn't provide it.",
        life_span: '12 - 15',
        indoor: 0,
        lap: 0,
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        cat_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 1,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 3,
        vocalisation: 5,
        bidability: 3,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Bengal_(cat)',
        hypoallergenic: 1,
      },
      {
        weight: {
          imperial: '6 - 15',
          metric: '3 - 7',
        },
        id: 'birm',
        name: 'Birman',
        cfa_url: 'http://cfa.org/Breeds/BreedsAB/Birman.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/birman',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/birman',
        temperament: 'Affectionate, Active, Gentle, Social',
        origin: 'France',
        country_codes: 'FR',
        country_code: 'FR',
        description:
          'The Birman is a docile, quiet cat who loves people and will follow them from room to room. Expect the Birman to want to be involved in what you’re doing. He communicates in a soft voice, mainly to remind you that perhaps it’s time for dinner or maybe for a nice cuddle on the sofa. He enjoys being held and will relax in your arms like a furry baby.',
        life_span: '14 - 15',
        indoor: 0,
        lap: 1,
        alt_names: 'Sacred Birman, Sacred Cat Of Burma',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 2,
        health_issues: 1,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 4,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Birman',
        hypoallergenic: 0,
      },
      {
        weight: {
          imperial: '6 - 11',
          metric: '3 - 5',
        },
        id: 'bomb',
        name: 'Bombay',
        cfa_url: 'http://cfa.org/Breeds/BreedsAB/Bombay.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/bombay',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/bombay',
        temperament: 'Affectionate, Dependent, Gentle, Intelligent, Playful',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          "The the golden eyes and the shiny black coa of the Bopmbay is absolutely striking. Likely to bond most with one family member, the Bombay will follow you from room to room and will almost always have something to say about what you are doing, loving attention and to be carried around, often on his caregiver's shoulder.",
        life_span: '12 - 16',
        indoor: 0,
        lap: 1,
        alt_names: 'Small black Panther',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 1,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 4,
        stranger_friendly: 4,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Bombay_(cat)',
        hypoallergenic: 0,
      },
      {
        weight: {
          imperial: '8 - 18',
          metric: '4 - 8',
        },
        id: 'bslo',
        name: 'British Longhair',
        temperament:
          'Affectionate, Easy Going, Independent, Intelligent, Loyal, Social',
        origin: 'United Kingdom',
        country_codes: 'GB',
        country_code: 'GB',
        description:
          'The British Longhair is a very laid-back relaxed cat, often perceived to be very independent although they will enjoy the company of an equally relaxed and likeminded cat. They are an affectionate breed, but very much on their own terms and tend to prefer to choose to come and sit with their owners rather than being picked up.',
        life_span: '12 - 14',
        indoor: 0,
        alt_names: '',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 4,
        grooming: 5,
        health_issues: 1,
        intelligence: 5,
        shedding_level: 1,
        social_needs: 3,
        stranger_friendly: 4,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/British_Longhair',
        hypoallergenic: 0,
      },
      {
        weight: {
          imperial: '12 - 20',
          metric: '5 - 9',
        },
        id: 'bsho',
        name: 'British Shorthair',
        cfa_url: 'http://cfa.org/Breeds/BreedsAB/BritishShorthair.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/british-shorthair',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/british-shorthair',
        temperament: 'Affectionate, Easy Going, Gentle, Loyal, Patient, calm',
        origin: 'United Kingdom',
        country_codes: 'GB',
        country_code: 'GB',
        description:
          "The British Shorthair is a very pleasant cat to have as a companion, ans is easy going and placid. The British is a fiercely loyal, loving cat and will attach herself to every one of her family members. While loving to play, she doesn't need hourly attention. If she is in the mood to play, she will find someone and bring a toy to that person. The British also plays well by herself, and thus is a good companion for single people.",
        life_span: '12 - 17',
        indoor: 0,
        lap: 1,
        alt_names: 'Highlander, Highland Straight, Britannica',
        adaptability: 5,
        affection_level: 4,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 2,
        grooming: 2,
        health_issues: 2,
        intelligence: 3,
        shedding_level: 4,
        social_needs: 3,
        stranger_friendly: 2,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 1,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/British_Shorthair',
        hypoallergenic: 0,
      },
      {
        weight: {
          imperial: '6 - 12',
          metric: '3 - 5',
        },
        id: 'bure',
        name: 'Burmese',
        cfa_url: 'http://cfa.org/Breeds/BreedsAB/Burmese.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/burmese',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/burmese',
        temperament:
          'Curious, Intelligent, Gentle, Social, Interactive, Playful, Lively',
        origin: 'Burma',
        country_codes: 'MM',
        country_code: 'MM',
        description:
          'Burmese love being with people, playing with them, and keeping them entertained. They crave close physical contact and abhor an empty lap. They will follow their humans from room to room, and sleep in bed with them, preferably under the covers, cuddled as close as possible. At play, they will turn around to see if their human is watching and being entertained by their crazy antics.',
        life_span: '15 - 16',
        indoor: 0,
        lap: 1,
        alt_names: '',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 4,
        grooming: 1,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Burmese_(cat)',
        hypoallergenic: 1,
      },
      {
        weight: {
          imperial: '6 - 13',
          metric: '3 - 6',
        },
        id: 'buri',
        name: 'Burmilla',
        cfa_url: 'http://cfa.org/Breeds/BreedsAB/Burmilla.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/burmilla',
        temperament:
          'Easy Going, Friendly, Intelligent, Lively, Playful, Social',
        origin: 'United Kingdom',
        country_codes: 'GB',
        country_code: 'GB',
        description:
          'The Burmilla is a fairly placid cat. She tends to be an easy cat to get along with, requiring minimal care. The Burmilla is affectionate and sweet and makes a good companion, the Burmilla is an ideal companion to while away a lonely evening. Loyal, devoted, and affectionate, this cat will stay by its owner, always keeping them company.',
        life_span: '10 - 15',
        indoor: 0,
        lap: 1,
        alt_names: '',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 4,
        energy_level: 3,
        grooming: 3,
        health_issues: 3,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 4,
        stranger_friendly: 3,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Burmilla',
        hypoallergenic: 0,
      },
      {
        weight: {
          imperial: '10 - 15',
          metric: '5 - 7',
        },
        id: 'cspa',
        name: 'California Spangled',
        temperament: 'Affectionate, Curious, Intelligent, Loyal, Social',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          'Perhaps the only thing about the California spangled cat that isn’t wild-like is its personality. Known to be affectionate, gentle and sociable, this breed enjoys spending a great deal of time with its owners. They are very playful, often choosing to perch in high locations and show off their acrobatic skills.',
        life_span: '10 - 14',
        indoor: 0,
        alt_names: 'Spangle',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 1,
        health_issues: 1,
        intelligence: 5,
        shedding_level: 1,
        social_needs: 3,
        stranger_friendly: 4,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/California_Spangled',
        hypoallergenic: 0,
      },
      {
        weight: {
          imperial: '7 - 12',
          metric: '3 - 5',
        },
        id: 'ctif',
        name: 'Chantilly-Tiffany',
        temperament: 'Affectionate, Demanding, Interactive, Loyal',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          'The Chantilly is a devoted companion and prefers company to being left alone. While the Chantilly is not demanding, she will "chirp" and "talk" as if having a conversation. This breed is affectionate, with a sweet temperament. It can stay still for extended periods, happily lounging in the lap of its loved one. This quality makes the Tiffany an ideal traveling companion, and an ideal house companion for senior citizens and the physically handicapped.',
        life_span: '14 - 16',
        indoor: 0,
        lap: 1,
        alt_names: 'Chantilly, Foreign Longhair',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 4,
        grooming: 5,
        health_issues: 1,
        intelligence: 5,
        shedding_level: 5,
        social_needs: 3,
        stranger_friendly: 4,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Chantilly-Tiffany',
        hypoallergenic: 0,
      },
      {
        weight: {
          imperial: '6 - 15',
          metric: '3 - 7',
        },
        id: 'char',
        name: 'Chartreux',
        cfa_url: 'http://cfa.org/Breeds/BreedsCJ/Chartreux.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/chartreux',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/chartreux',
        temperament:
          'Affectionate, Loyal, Intelligent, Social, Lively, Playful',
        origin: 'France',
        country_codes: 'FR',
        country_code: 'FR',
        description:
          'The Chartreux is generally silent but communicative. Short play sessions, mixed with naps and meals are their perfect day. Whilst appreciating any attention you give them, they are not demanding, content instead to follow you around devotedly, sleep on your bed and snuggle with you if you’re not feeling well.',
        life_span: '12 - 15',
        indoor: 0,
        lap: 1,
        alt_names: '',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 2,
        grooming: 1,
        health_issues: 2,
        intelligence: 4,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 1,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Chartreux',
        hypoallergenic: 1,
      },
    ],
  });
